#ifndef ADC_H_
#define ADC_H_

#include "PinDefs.h"

//How many knobs do I need?
typedef enum
{
	ANALOG_OSC1_WAVEFORM = 0,
	ANALOG_OSC2_WAVEFORM,
	ANALOG_OSC1_DUTY_CYCLE,
	ANALOG_OSC2_DUTY_CYCLE,
	ANALOG_DETUNE_CENTS,
	ANALOG_DETUNE_SEMIS,
	ANALOG_DETUNE_OCTAVE,
	ANALOG_DETUNE_PHASE,
	ANALOG_OSC1_LEVEL,
	ANALOG_OSC2_LEVEL,
	ANALOG_LFO_RATE,
	ANALOG_LFO_DEPTH,
	ANALOG_DELAY_TIME,
	ANALOG_ATTACK_RATE,
	ANALOG_DECAY_RATE,
	ANALOG_SUSTAIN_LEVEL,
	ANALOG_RELEASE_RATE,
	ANALOG_SEQUENCE_RATE,
	TOTAL_ANALOG_READINGS //This many
}ANALOG_READING;

void ADC_Init();

void ADC_Update();

#endif /* ADC_H_ */